### ISSUE TITLE
Question for Vssue

### ISSUE THREAD

**Issue by gngchrs** [meteorlxy/vuepress-theme-meteorlxy#33]
Hi, 

Whenever I enable comments, theme automatically redirects someone to login with github when they visit a post page. 

Has anyone experienced this? Post page automatically redirecting to github, without user explicitly saying they want to comment.

**Comment by meteorlxy** [comment]
You have to create the corresponding issue correctly to make Vssue work. If the issue does not exist, Vssue will try to create it (login to github first).

Or you need to turn `autoCreateIssue` off, so that Vssue won't try to create one, and the comments won't work if you don't create the issue manually.
