### ISSUE TITLE
about i18n

### ISSUE THREAD

**Issue by tgmti** [meteorlxy/vuepress-theme-meteorlxy#8]
Hello Friend,

I would like to help add i18n for standard pages (like in Categories.vue title).

My intention is add en-US and pt-BR.

I tried using the 'vue-i18n' plugin, based on your implementation of vssue plugin, but could not find a right entry point for include 'vue-i18n' in root whith elegant way.

I've tried with [enhanceappfiles](https://v1.vuepress.vuejs.org/plugin/option-api.html#enhanceappfiles) and [clientrootmixin](https://v1.vuepress.vuejs.org/plugin/option-api.html#clientrootmixin).

I'm thinking of following the same strategy used in Default Theme.

Do you suggest something different?

tnks!

Ps.: Sorry my wrong english.

**Comment by meteorlxy** [comment]
Thanks for your interests.

The strategy used in the default theme is a possible solution : translate the text in the `themeConfig` by the users themselves. In this way, our theme only need to load the text from the `themeConfig`.

`vue-i18n` is another choice, because we have more text need to be translated than the default theme.

But I've not tried `vue-i18n` in Vuepress yet. As you feedback, there might be some problems to make them work together.

PS: Never mind, my english is not so good, too . 😂 

PPS: Would you like to help Vssue support pt-BR, too? 😄

**Comment by meteorlxy** [comment]
What about this way:

- We provide languages files in `lib/langs/` dir:

```
+-- lib/
    +-- langs/
        +-- pt-BR.js
        +-- en-US.js
        +-- zh-CN.js
        ....
```

- Users choose language in `themeConfig`:

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    lang: require('vuepress-theme-meteorlxy/lib/langs/en-US'),
  },
}
```

- If the language is not supported, users can set manually in `themeConfig`:

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    lang: {
      hello: 'hola',
    },
  },
}
```

- Also, users can override some fields:

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    lang: Object.assign(require('vuepress-theme-meteorlxy/lib/langs/en-US'), {
      hello: 'hola',
    }),
  },
}
```

**Comment by tgmti** [comment]
Liked it.

at night i´ll look this (i´m in gmt-3 time zone)

Vssue support pt-BR, too? 😄
sure! in progress too ! 

Thanks for availability

**Comment by meteorlxy** [comment]
GMT+8 here, 11 hours away 😄 

FYI, you can check language files of Vssue [here](https://github.com/meteorlxy/vssue/tree/master/packages/vssue/src/i18n/lang).

**Comment by meteorlxy** [comment]
@tgmti 

Close this as i18n is supported in 1.0.0-alpha.15 :tada:

Feedback welcome if you have any ideas about that

**Comment by tgmti** [comment]
thanks a lot!

later I´ll apply in my project, and will work to send PR with pt-BR too
